version: '3.2'

services:
  openkm:
    image: openkm/openkm-ce:6.3.12
    ports:
      - "8443:8443"
    volumes:
      - ${PWD}/server.xml:/opt/tomcat/conf/server.xml
      - ${PWD}/OpenKM.cfg:/opt/tomcat/OpenKM.cfg
      - ${PWD}/.keystore:/opt/tomcat/.keystore
      - ${PWD}/repository:/opt/tomcat/repository
    links:
      - mysql:mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_bin --init-file=/opt/init_file/init_file.sql
    environment:
      - MYSQL_ROOT_PASSWORD=openkm
    expose:
      - 3306
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    volumes:
      - ${PWD}/mysql:/var/lib/mysql
      - ${PWD}/init_file.sql:/opt/init_file/init_file.sql
